### PR TITLE
Add autoResize flag to the `create` api docs

### PR DESCRIPTION
**Pull request by namirsab**
As the title says, adding just a small bit of documentaton of a really helpful feature.

### CODE REVIEW

**Comment by bluepnume** [comment]
Looks great -- could you also add a note about enabling for just height/width? For example, it's possible to do:

```javascript
autoResize: {
    width: false,
    height: true
}
```

Thanks again!

**Comment by twig-openlearning** [comment]
This was just the feature I was trying to implement until I looked on github.
Updated docs would be highly appreciated

**Comment by namirsab** [comment]
@bluepnume done!

Note: @twig-openlearning this is happening probably not only to you, but to many people. That's why I started docs as I discover things. I really think this project has a lot of value, but without proper docs it's really difficult to start with. So, please, I encourage you to do the same!

**Comment by bluepnume** [comment]
Awesome, thanks!

**Pull request merged**
